import React from 'react';

const RaceCorporation = () => {
  const racingPartners = [
    { name: 'Ferrari', logo: 'ferrari_logo.png' }, // Replace with actual logo paths
    { name: 'Alfa Romeo', logo: 'alfa_romeo_logo.png' },
    { name: 'Lamborghini', logo: 'lamborghini_logo.png' },
    { name: 'Ducati', logo: 'ducati_logo.png' },
    { name: 'Maserati', logo: 'maserati_logo.png' },
    { name: 'Bugatti', logo: 'bugatti_logo.png' },
  ];

  const coreValues = [
    'Innovation',
    'Precision',
    'Teamwork',
    'Excellence',
    'Passion',
    'Integrity',
    'Sustainability'
  ];

  const corporationInfo = {
    name: 'Race Corporation',
    mission: 'To push the boundaries of racing technology and performance.',
    vision: 'To be the leading force in motorsports innovation and sustainable racing.',
    contact: {
      email: 'info@racecorp.com',
      phone: '+1 555-RACE',
      address: '1 Racing Lane, Speed City, USA'
    },
  };

  return (
    <div style={{ fontFamily: 'Arial, sans-serif', padding: '20px' }}>
      <h1>{corporationInfo.name}</h1>
      <p><strong>Mission:</strong> {corporationInfo.mission}</p>
      <p><strong>Vision:</strong> {corporationInfo.vision}</p>

      <h2>Racing Partners</h2>
      <div style={{ display: 'flex', flexWrap: 'wrap', gap: '20px' }}>
        {racingPartners.map((partner) => (
          <div key={partner.name} style={{ textAlign: 'center' }}>
            <img
              src={partner.logo}
              alt={`${partner.name} Logo`}
              style={{ maxWidth: '100px', maxHeight: '100px' }}
            />
            <p>{partner.name}</p>
          </div>
        ))}
      </div>

      <h2>Core Values</h2>
      <ul style={{ listStyleType: 'disc', marginLeft: '20px' }}>
        {coreValues.map((value) => (
          <li key={value}>{value}</li>
        ))}
      </ul>

      <h2>Contact Information</h2>
      <p><strong>Email:</strong> {corporationInfo.contact.email}</p>
      <p><strong>Phone:</strong> {corporationInfo.contact.phone}</p>
      <p><strong>Address:</strong> {corporationInfo.contact.address}</p>

      <footer style={{ marginTop: '20px', textAlign: 'center', borderTop: '1px solid #ccc', paddingTop: '10px' }}>
        &copy; {new Date().getFullYear()} Race Corporation. All rights reserved.
      </footer>
    </div>
  );
};

export default RaceCorporation;
